### ISSUE TITLE
Run selection

### ISSUE THREAD

**Issue by ded0rggit** [tconbeer/harlequin#155]
Harlequin with latest duckdb on fedora 38.
Is it possible to run a selection from an sql scirpt file rather than the whole file?
Apologies if I am missing somehting very obvious.

**Comment by tconbeer** [comment]
Here's how I'd like to do this:

when the selection changes, have duckdb parse the selection (see #131 ). If it's a valid query, change the "Run Query" button to say "Run Selection" and on click or ctrl+enter, run the selection instead. Shouldn't be hard to manage the state with a few reactive vars.

**Comment by tconbeer** [comment]
#34 is kind of related -- with that we'd only execute the query at the cursor, and not execute other queries (separated by semicolons) in the editor.

**Comment by tconbeer** [comment]
This has been released in v0.0.23
