### ISSUE TITLE
Improve support for Key Bindings in VSCode Terminal

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin#229]
Would help run inside codespaces.

**Comment by tconbeer** [comment]
Seems like only some bindings get preempted by VS Code:
- ctrl+j hides/shows terminal
- f1 is command palette
- f5 selects debugger
- f6 moves focus to the footer
- ctrl+q opens the quick menu
- ctrl+e searches files by name
- ctrl+k starts a chord

**Comment by tconbeer** [comment]
We could detect we're running in VSCode and remap the keys?

```python
import os

if os.getenv("TERM_PROGRAM") == 'vscode':
    ...
```

Or more broadly, provide cli options for different bindings, (emacs, vim, etc.) -- not quite sure how that would work, since bindings is a classvar on Harlequin... I think we'd have to subclass Harlequin and instantiate the right one in cli.py. Or we could hijack whatever API consumes the classvar.

**Comment by tconbeer** [comment]
This is mostly solved by changing VS Code settings; I've added instructions to the docs.

**Comment by lkuoch** [comment]
Having a option in the `.toml` file to override keybindings would help with this

**Comment by tconbeer** [comment]
You can configure VS Code to make this work. See here: https://harlequin.sh/docs/troubleshooting/key-bindings
