### ISSUE TITLE
Incorrect Border Rendering on Windows 10 Terminal - PowerShell

### ISSUE THREAD

**Issue by MoeJD** [tconbeer/harlequin#237]
![image](https://github.com/tconbeer/harlequin/assets/76531825/6275d5b6-10ce-41f8-93d9-2a85669f61a8)

After installing Harlequin via pipx and running it using `pipx run harlequin` The borders are being rendered using incorrect glyphs.

Any thoughts on how to get around this, really looking forward to using this after resolving this issue.

Thank you for your time.

**Comment by tconbeer** [comment]
yikes, that looks terrible. As a first step, can you try a different font? I use FiraCode, but most will monos will work.

Are you running harlequin in windows or WSL?

**Comment by MoeJD** [comment]
I am running it from Windows Terminal, not in WSL.

After downloading and setting FiraCode as my font I am still seeing this issue unfortunately, but I really like the font so thank you for that recommendation haha.

![image](https://github.com/tconbeer/harlequin/assets/76531825/35f65c41-17ef-46fc-9ae8-e525f941e66c)

Do you think there is any issue with running this from `pipx run harlequin` instead of just `harlequin` ? After running `pipx install harlequin` I am not able to call it directly which is why I'm running it the other way.

**Comment by tconbeer** [comment]
I'm on Windows 11, but I can't repro using that font (I'm actually loving your font too). This is Powershell in Windows Terminal:
![image](https://github.com/tconbeer/harlequin/assets/705906/01f9f77b-5050-4a01-baa4-3a9a2514f7b8)

I'm also using the Atlas Engine, but I don't think that matters.

Here are my settings:
![image](https://github.com/tconbeer/harlequin/assets/705906/b69c0219-56c7-41fc-bab0-529fa7b1cca9)

**Comment by MoeJD** [comment]
Darn, I set mine to the exact same setting with no luck. 

![image](https://github.com/tconbeer/harlequin/assets/76531825/7189b482-e4ab-4b5d-81b7-7518a056fae4)

I'm drawing a blank here, Even reverted the Font size to 12 just to be 100% inline with your settings.

**Comment by MoeJD** [comment]
By running it via `pipx run harlequin` is it operating in a virtual environment or something and unable to use the defaults from the terminal?

**Comment by tconbeer** [comment]
I don't think it's pipx. 

Any other terminals on your machine? Maybe the VS Code terminal? Otherwise I think I'd have to open an issue with Textual.

**Comment by MoeJD** [comment]
I can try it in VS Code.

![image](https://github.com/tconbeer/harlequin/assets/76531825/3a53451e-82dc-4059-bc5d-58f5c4d147e8)

Seems like the same issue unfortunately.

**Comment by tconbeer** [comment]
I wonder if it could be a locale thing. What is your default encoding?

In powershell:
```
[System.Text.Encoding]::Default
```

**Comment by MoeJD** [comment]
Here is a screen shot of that command.

![image](https://github.com/tconbeer/harlequin/assets/76531825/588e4575-e04b-40ae-975a-6f775862fa64)

**Comment by tconbeer** [comment]
Same as me. Let's take this to Textual

**Comment by MoeJD** [comment]
Just wanting to double check on this as I don't open very many issues, Did you want me to create an issue over at Textual or have you already done that?

Thank you again for all of your help in this!

**Comment by davep** [comment]
Just because the above issue link will make it look like it's been closed; that's because it's been moved to this discussion: https://github.com/Textualize/textual/discussions/3375

**Comment by tconbeer** [comment]
I'm going to close this, since the discussion was productive. If anyone finds this in the future, it seems likely that the Python environment was corrupted and a very old version of textual was being invoked on this user's machine.
