### ISSUE TITLE
Running in a container - issue with display updating / blitting / flicker

### ISSUE THREAD

**Issue by mskyttner** [tconbeer/harlequin#273]
So nice with harlequin running anywhere! I wanted to run it in a container. I tried building a [container image with harlequin](https://github.com/mskyttner/harlequin/blob/main/Dockerfile) (also in a web-enabled variant running under tty2web) and running it I noted some issues when running the query "select 1;". 

Sometimes results appear but often not. Not sure what causes this... occasionally it works. Could it be some kind of textual rendering issue (it looks like there is a quick flicker but the display is not properly updated)?

To replicate (use either "docker" or "podman"):

```
docker run --rm -it ghcr.io/mskyttner/harlequin harlequin
# then enter query "select 1" and press either "run query button" or press ctrl + j

docker run --rm -it -p "80:1294" ghcr.io/mskyttner/harlequin
# then open browser at http://localhost
```

Screenshots:

Running in container shell often the result of running the query doesn't appear:
![image](https://github.com/tconbeer/harlequin/assets/1715840/284198b7-380a-4472-b3de-9cc0b34eefe1)

Running in browser (under tty2web) shows same behavior:
![image](https://github.com/tconbeer/harlequin/assets/1715840/63a88b3f-c0a1-48ef-a9e6-cb4e676c1582)

**Comment by tconbeer** [comment]
What terminal and shell is this? I think of you SSH into the container with a modern terminal this should work fine; last I tried the default Docker terminal isn't great and I think launches sh

**Comment by tconbeer** [comment]
See also: https://harlequin.sh/docs/troubleshooting

**Comment by mskyttner** [comment]
The web tty is provided via xterm.ts, resizing and such seem fine. I could use some other shell in the non-web container if that would alleviate the issues. Any recommendations? I tested the non-web variant of the harlequin container using terminator and also whatever the default terminal app is in Linux Mint.

**Comment by mskyttner** [comment]
Strangely it often seems to work better if I use another query than "select 1;"

![image](https://github.com/tconbeer/harlequin/assets/1715840/81891047-e709-4f77-a405-10614bbc1326)

**Comment by mskyttner** [comment]
oops sorry, I by mistake attempted to merge a branch from my fork to the wrong repo by accident... please remove or ignore that one...

It looks that setting the COLORTERM  to truecolor makes a difference for the better though.

```
podman run -p "1294:1294" --rm -it harlequin 
# and open browser at http://localhost:1294
```

Gives:

![image](https://github.com/tconbeer/harlequin/assets/1715840/0847bae8-504e-44b2-96c4-1bf4adf02f92)

**Comment by tconbeer** [comment]
@mskyttner I noticed you like ending your queries with `;` ... I actually just fixed this in my branch, but if your cursor is right **after** the semicolon, the query won't execute (since we think you're trying to execute the query where the cursor is, which in this case is just blank). Could that be the cause?

**Comment by mskyttner** [comment]
This seems to be the case! Knowing about this now, it works quite smoothly also in the containerized web-enabled variant... just a few keybinding collisions (Ctrl+Enter doesn't come through, but Ctrl+J works) so mostly both mouse and shortcuts works well even in the browser. Now I just have to figure out how to configure a nice webfont. Even when trying to force a custom webfont in tty2web I seem to be getting this Courier like font. I wonder if harlequin/textual has its own css that overrides this setting... 

Thanks for the help!
