### ISSUE TITLE
add theme option to CLI

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin#33]
https://rich.readthedocs.io/en/stable/syntax.html#theme

**Comment by bjornasm** [comment]
Just wondering - are these issues intended as todo items, and are they up for grabs for anyone who want to contribute?

**Comment by tconbeer** [comment]
@bjornasm Both! Although this one (and some others) will be mostly handled in this repo, instead: https://github.com/tconbeer/textual-textarea. I'll create a tag for those

**Comment by bjornasm** [comment]
Thank you for your answer! Sorry for the meta discussion in this issue. This tool is incredible, and much needed! Would love to contribute.

**Comment by tconbeer** [comment]
closed by #80
