### ISSUE TITLE
password contain @ raise error

### ISSUE THREAD

**Issue by wonb168** [tconbeer/harlequin#354]
my password contain @, then use two methods , both raise error:

`harlequin -a postgres "postgresql://ur:cp2023%40$!@10.204.128.93:10086/scp"`
zsh: event not found: @10.204.128.93

or,
`harlequin -a postgres -h 10.204.128.93 -p 10086 -U ur --password scp2023@$! -d scp`
connection to server at "10.204.128.93", port 10086 failed: FATAL:  password authentication failed for user "ur"

BUT, this password is right, why?

**Comment by tconbeer** [comment]
This is really an issue with Psychopg2, the pg driver. Try using --password and quoting the value. Other ideas for escapes here: https://stackoverflow.com/questions/77184491/psycopg2-how-to-deal-with-special-characters-in-password

**Comment by tconbeer** [comment]
I just tested this and `--password "scp2023@$!"` works fine

**Comment by wonb168** [comment]
> I just tested this and `--password "scp2023@$!"` works fine

NOT work,
<img width="436" alt="image" src="https://github.com/tconbeer/harlequin/assets/25274931/c922beac-8425-4793-b1cb-ade15aae6dd1">

**Comment by tconbeer** [comment]
Ok, what shell, terminal, and os? Might need single quotes if your shell is trying to interpolate something.

**Comment by wonb168** [comment]
macos14
iterm2：
<img width="680" alt="image" src="https://github.com/tconbeer/harlequin/assets/25274931/a5947bec-5d07-4201-a409-c35a71cd4ad1">

OK, I tried。double quote is not ok，need singe qutoe。
