### ISSUE TITLE
BigQuery adapter

### ISSUE THREAD

**Issue by joshtemple** [tconbeer/harlequin#363]
Noting that I've started work on a BigQuery adapter over [here](https://github.com/joshtemple/harlequin-bigquery).

Lots of edges and TODOs, but the required methods are implemented and it does work.

**Comment by tconbeer** [comment]
Yesss! Legend! Lmk if you'd like any help

**Comment by joshtemple** [comment]
Hey @tconbeer I've released v1 on PyPi! I'm sure there are some lingering issues but it's good enough for folks to start kicking the tires. Thanks for the adapter framework, it was well-documented and easy to follow. This was a fun project!

**Comment by joshtemple** [comment]
Realizing I was possibly supposed to submit some docs PRs? Let me know where I should point those (or feel free to just do it yourself it that's easier!)

**Comment by tconbeer** [comment]
Amazing, thank you so much!

I'm happy to make a basic update to the docs; the docs source is here, though: https://github.com/tconbeer/harlequin-web
