### ISSUE TITLE
Refresh data catalog on demand

### ISSUE THREAD

**Issue by joshtemple** [tconbeer/harlequin#375]
It would be useful to have a keybinding and/or a UI button to refresh the data catalog manually. For example, when iterating on code that modifies a table's schema in SQLite, I want to see these changes reflected in Harlequin without having to quit and restart the app entirely.

**Comment by tconbeer** [comment]
Right now we refresh the catalog if Harlequin executes a query that doesn't return results (like most DDL). Maybe there's a bug in the SQLite adapter so that isn't working? Can you share your queries that aren't causing a refresh?

**Comment by joshtemple** [comment]
In my case, I’m running the DDL externally through a Python script, but then want to see the new tables in Harlequin before I query them.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am9zaC50ZW1wbGUwMzJAZ21haWwuY29t>

**Comment by tconbeer** [comment]
Ohhh that makes sense. I'm good to add a key binding.

**Comment by tconbeer** [comment]
released in v1.11.0
