### ISSUE TITLE
FR: Redshift Adapter

### ISSUE THREAD

**Issue by deblnia** [tconbeer/harlequin#385]
Big fan of the project! Any interest in a Redshift adapter? 

I'll try and start one soon 😄

**Comment by tconbeer** [comment]
I think the Postgres adapter should work with Redshift. I haven't tried it, but it uses psycopg2 under the hood, and I used to use that library to connect with Redshift.

**Comment by vpascal** [comment]
Tested i! Works fine with postgress!

**Comment by tconbeer** [comment]
Awesome, will add to docs
