### ISSUE TITLE
Refactor export; make adapter-agnostic

### ISSUE THREAD

**Issue by matsonj** [tconbeer/harlequin#413]
**Describe the bug**
When connected to a database (in my case, SQL Server) with the odbc driver, you cannot export data with ctrl+e, even though the data is clearly exposed in the interface.

**To Reproduce**
1. connect to harlequin with odbc connector
2. run any query
3. press "ctrl+e" to export the data
4. you will get an error

**Expected behavior**
data exports as csv.

**Actual behavior**
you get this error.
![image](https://github.com/tconbeer/harlequin/assets/16811433/1f50a1d6-34a9-41f4-ade3-8ddfe54eb81e)

**Additional context**

What database adapter are you using with Harlequin? ODBC

Can you tell us more about your system?
- Shell: Powershell
- Terminal: Windows Terminal
- OS of the shell: Windows 11 (native)
- OS of the terminal (if different from the shell):

**Comment by matsonj** [comment]
I recognize this is actually a feature request, sorry in advance @tconbeer

**Comment by tconbeer** [comment]
Yeah this is expected for now. I actually think I'm going to change the whole export thing to just export the data in the table, since we already have that locally in Arrow. Would that work for you or do you expect something closer to a COPY TO statement?

**Comment by matsonj** [comment]
Yeah I don't think 'copy to' is the right path. Since the data is already in arrow locally, it's makes more sense to me to use those libraries to export to csv etc.

**Comment by tconbeer** [comment]
Yeah, ok that's good validation. In the meantime, ctrl+a and ctrl+c will work for datasets that aren't too huge.
