### ISSUE TITLE
run harlequin --no-download-tzdata on windows Cmder abnormal

### ISSUE THREAD

**Issue by l1t1** [tconbeer/harlequin#468]
**Describe the bug**
at first, I  input `select version()`, but the `run query` button is not exsits, after press `Ctrl+J`, the `run query` button is displayed, but the sql input disappeared,

**To Reproduce**
run harlequin --no-download-tzdata on windows Cmder

**Expected behavior**
it always shows the sql editor and the  `run query` button

**Actual behavior**
at first, I  input `select version()`, but the `run query` button is not exsits, after press `Ctrl+J`, the `run query` button is displayed, but the sql input disappeared,
![first_2024-02-18_083110](https://github.com/tconbeer/harlequin/assets/23301704/7de543a8-75ab-43a5-8001-38c3971ee0a6)
![after_2024-02-18_083223](https://github.com/tconbeer/harlequin/assets/23301704/aaee6cb9-519b-4a78-89d4-69937129e771)

**Additional context**
What is the output of `harlequin --version`?
```
harlequin, version 1.15.0

Installed Adapters:
  - duckdb, version 1.15.0
  - sqlite, version 1.15.0
```
What database adapter are you using with Harlequin? (Default is DuckDB)
DuckDB
Can you tell us more about your system?
- Shell:
- Terminal:Cmder
- OS of the shell:Windows 7
- OS of the terminal (if different from the shell):Windows 7

For example, for my system, these are:
- Bash
- Windows Terminal
- Ubuntu 22.04 / WSL2
- Windows 11

**Comment by tconbeer** [comment]
Windows 7 was EOL 4 years ago; I'm sorry but you're on your own for this one. I did briefly try cmder on Windows 11, but it doesn't really work; it doesn't resize the windows properly, mouse input isn't accepted, etc. I recommend upgrading to Windows 10+ and using Windows Terminal.
