### ISSUE TITLE
Error:  ArrowInvalid Schema at index 0 was different

### ISSUE THREAD

**Issue by costructuralist** [tconbeer/harlequin#482]
Hi!  Thanks for this beatiful software.

I'm getting an error running the following query on a DuckDB database on a network mapped drive (not sure if that is relevant):

```sql
select * from sis.FCT_ModuleEnrolments ME
join sis.DIM_Programme DP on DP.ProgrammeKey = ME.ProgrammeKey
limit 1000
```

The error is:

```
ArrowInvalid('Schema at index 0 was different: <schema details follow...>
```

The `sis.FCT_ModuleEnrolments` table is quite large, and looking around it might have to do with chunking (https://github.com/aws/aws-sdk-pandas/issues/2433)

I can provide the whole error dump if needed.

**Comment by tconbeer** [comment]
I can't reproduce with this info. Can you please use the bug report template and try to provide a reproducible example?
