### ISSUE TITLE
Make `--config` support `NO_COLOR`

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin#552]
We manually set the styling for questionary... should check NO_COLOR env var first.

See: https://github.com/tconbeer/harlequin/discussions/549

**Comment by vlnn** [comment]
Actually themes are also working a bit strange while config, e.g. in light themed terminal active/unactive menu items are pretty hard to tell apart. 
Iterm:
![CleanShot 2024-06-06 at 09 10 54@2x](https://github.com/tconbeer/harlequin/assets/29273499/7b9c3f8f-32d0-4400-80cb-c1d7ad32b9e6)
Terminal.app:
![CleanShot 2024-06-06 at 09 11 44@2x](https://github.com/tconbeer/harlequin/assets/29273499/2e20554e-ea47-41e7-a5e8-e7bff59380b9)
