### ISSUE TITLE
Error authenticating DuckDb to S3 using AWS credentials provider 

### ISSUE THREAD

**Issue by james-n-centric** [tconbeer/harlequin#615]
**Describe the bug**
I'm getting an authentication error while trying to read parquet files through DuckDb. If I use the DuckDb command line tool, the read works, but doing exactly the same in Harlequin fails.
The error is a 400, which is what I get if I try to read S3 without using any credentials.

**To Reproduce**
Authenticate to AWS using SSO or set env to hold AWS credentials
Test this is working using: aws s3 ls (returns list of buckets)

Login to new Duckdb using DuckDb command line.
Run: call load_aws_credentials()
Run: select * from read_parquet('s3://path_to_file'); (read file successfully)
Run: .quit

Login to same Duckdb using Harlequin
Run: call load_aws_credentials()
Run: select * from read_parquet('s3://path_to_file'); (returns error:)

HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=cloud-audit%2Faws%2Fcsv%2Falbs%2F' (HTTP 400))

In Harlequin, if I manually create a SECRET using the key, secret key and session token, the 'select * from read_parquet' query now works.

 

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [ ] Maybe
- [ X] No

**Additional context**
*Please provide as much as you can, but don't waste your time if it's definitely not relevant or you don't know.*

What is the output of `harlequin --version`?
1.23.1

What database adapter are you using with Harlequin? (Default is `duckdb`)
DuckDb

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).
None

Can you tell us more about your system?
- Shell: zsh
- Terminal: mac os default
- OS of the shell: mac
- OS of the terminal (if different from the shell):
- Default locale / language for your OS/Terminal/Shell:

How did you install Harlequin?
- [ ] pipx
- [ ] conda/mamba
- [ X] pip (global install)
- [ ] pip + venv/virtualenv or pipenv
- [ ] Poetry
- [ ] uv/Rye
- [ ] other: _____________

**Comment by tconbeer** [comment]
Actually, re-reading your report, I think you may just need to install and load the AWS extension. The latest versions of DuckDB don't require the AWS extensions and offer a new api that doesn't use `call load_aws_credentials()`

**Comment by james-n-centric** [comment]
OK, I did a clean install on a new virtual env (boto3, duckdb and harlequin) and it worked correctly, so it must have been something to do with versions.

But you do still need to use: call load_aws_credentials() or it will not inherit anything from the boto session.

Thanks for you're reply.
