### ISSUE TITLE
Text drifts to the right after commenting and uncommenting

### ISSUE THREAD

**Issue by harrymconner** [tconbeer/harlequin#616]
**Before Proceeding, please acknowledge**:
- [x] I have consulted the [Troubleshooting guide](https://harlequin.sh/docs/troubleshooting/index).
- [x] I have searched Issues and Discussions in this repo.
- [x] Feature requests should be initiated as Discussions. This is a bug report.

**Describe the bug**
Commenting and un-commenting a query causes the text to drift to the right.

**To Reproduce**
Comment and uncomment a query multiple times using ctrl + /

**Expected behavior**
The text is commented and uncommented and remains "in place".

**Actual behavior**
The text drifts to the right by one character after each comment and uncomment.

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [x] Maybe
- [ ] No

**Additional context**
N/A

What is the output of `harlequin --version`?
harlequin, version 1.23.1

Installed Adapters:
  - duckdb, version 1.23.1
  - sqlite, version 1.23.1

What database adapter are you using with Harlequin? (Default is `duckdb`)
duckdb

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).
N/A

Can you tell us more about your system?
- Shell: Powershell
- Terminal: Windows Terminal
- OS of the shell: Windows
- OS of the terminal (if different from the shell):
- Default locale / language for your OS/Terminal/Shell: en_US/UTF-8

> [!TIP]
> For example, for my system, these are:
> - Bash
> - Windows Terminal
> - Ubuntu 22.04 / WSL2
> - Windows 11
> - en_US/UTF-8

How did you install Harlequin?
- [x] pipx
- [ ] conda/mamba
- [ ] pip (global install)
- [ ] pip + venv/virtualenv or pipenv
- [ ] Poetry
- [ ] uv/Rye
- [ ] other: _____________

**Comment by tconbeer** [comment]
Thanks for the report. This must be a regression related to a recent Textual update.
