### ISSUE TITLE
Add Support to Hide or Disable the Data Catalog Pane

### ISSUE THREAD

**Issue by Nicoretti** [tconbeer/harlequin#618]
### Description

Implement a feature to toggle the visibility of the data catalog pane. In addition to showing and hiding the data catalog, updating the catalog could be paused too, while the data catalog is hidden. Ideally, this functionality can be toggled through a keyboard shortcut.

### Feature Requirements
- **Toggle Data Catalog Visibility:** Ability to show/hide the data catalog pane through a keyboard shortcut.
- **Pause Updates (optional):** When the data catalog is hidden, any updates to the catalog should be paused to enhance performance.

### Reasoning

- **Power Users:** Advanced users who are familiar with the structure of their data might not need to constantly view the catalog.
- **Additional Space:** Hiding the data catalog pane can provide more screen real estate for other tasks.
- **Occasional Use:** The data catalog is only necessary when users need to reference data structure, which is not always required.

### Background

I recently conducted a small [spike](https://github.com/Nicoretti/harlequin-exasol) to assess the feasibility and effort required to support Exasol in Harlequin. A few individuals have already tried it out, and some feedback indicated that the data catalog was consuming unnecessary space, [see here](https://github.com/Nicoretti/harlequin-exasol?tab=readme-ov-file#-ideas).

:spiral_notepad:  **_Note:_** 
_If you think this feature aligns with your vision for Harlequin, let me know. I would consider creating a PR for this._

**Comment by tconbeer** [comment]
You can already do this with F9 or ctrl+b

**Comment by Nicoretti** [comment]
@tconbeer 😅  apologies. I should have noticed that.
