### ISSUE TITLE
Harlequin freezes in context menu

### ISSUE THREAD

**Issue by DasFaultier** [tconbeer/harlequin#668]
**Before Proceeding, please acknowledge**:
- [x] I have consulted the [Troubleshooting guide](https://harlequin.sh/docs/troubleshooting/index).
- [x] I have searched Issues and Discussions in this repo.
- [x] Feature requests should be initiated as Discussions. This is a bug report.

**Describe the bug**
Harlequin uses 100% CPU resources of one CPU core and becomes unresponsive when using an item from the context menu to explore an SQLite database.

**To Reproduce**

1. Create a copy of any SQLite DB to experiment with. (I've done this with Firefox's `bounce-tracking-protection.sqlite` and an SQLite DB that is created and used by one of our internal applications at work.)
1. Open the BD in Harlequin using `harlequin -a sqlite dbname.sqlite`.
1. Using the left pane , navidate to any table of that DB and press `.` to open the context menu.
1. Pick an item from the context menu (I was interested in "Preview Data" and "Describe", the behaviour was the same.)
1. Run the chosen item and watch Harlequin freeze and eat up 100% of a CPU core. I had to send it a `SIGTERM` to exit Harlequin.

**Expected behavior**
Do not freeze. :)

**Actual behavior**
Does freeze. :)

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [ ] Maybe
- [x] No, I unfortunately don't speak Python -.-

**Additional context**
*Please provide as much as you can, but don't waste your time if it's definitely not relevant or you don't know.*

What is the output of `harlequin --version`?
```
harlequin, version 1.25.0
Installed Adapters:
  - duckdb, version 1.25.0
  - sqlite, version 1.25.0
```

What database adapter are you using with Harlequin? (Default is `duckdb`)
SQLite only

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).
None.

Can you tell us more about your system?
I've tried this on two separate systems to verify that this is not an issue with PuTTY or the SSH session.
System 1: 
- Shell: bash 5.2.15(1)
- Terminal: SSH connection using mRemote 1.76.20.24615 with PuTTY 0.81 
- OS of the shell: Debian 12 Bookworm, latest patches installed
- OS of the terminal (if different from the shell): Windows 10 Edu 22H2
- Default locale / language for your OS/Terminal/Shell: en_US.UTF-8

System 2:
- Shell: bash 5.1.16(1)
- Terminal: Gnome-Terminal 3.44.0 for Gnome 42
- OS of the shell: Linux Mint 21.3
- Default locale / language for your OS/Terminal/Shell: de_DE.UTF-8

> [!TIP]
> For example, for my system, these are:
> - Bash
> - Windows Terminal
> - Ubuntu 22.04 / WSL2
> - Windows 11
> - en_US/UTF-8

How did you install Harlequin?
- [x] pipx (on System 2)
- [ ] conda/mamba
- [ ] pip (global install)
- [x] pip + venv/virtualenv or pipenv (on System 1)
- [ ] Poetry
- [ ] uv/Rye
- [ ] other: _____________

**Comment by tconbeer** [comment]
Thanks for the report; something seems wrong with message handling -- I wonder if this could be related to #659
