### ISSUE TITLE
Color issue with single quotes

### ISSUE THREAD

**Issue by hacherix** [tconbeer/harlequin#689]
**Before Proceeding, please acknowledge**:
- [x] I have consulted the [Troubleshooting guide](https://harlequin.sh/docs/troubleshooting/index).
- [x] I have searched Issues and Discussions in this repo.
- [x] Feature requests should be initiated as Discussions. This is a bug report.

**Describe the bug**
When a string ends with `%'` it creates color issues.

**To Reproduce**
Use the following queries:
```
select *
from table
where col like '%hello'
and col2 = 290
and col2 not true;

select *
from table
where col like '%hello%'
and col2 = 290
and col2 not true;
```

**Expected behavior**
Pink color should not go beyond the single quotes.

**Actual behavior**
![image](https://github.com/user-attachments/assets/d5cee0c8-4b18-4288-8f8e-86d56e904b90) 

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [ ] Maybe
- [ ] No

**Additional context**

What is the output of `harlequin --version`?
```
harlequin, version 1.25.2

Installed Adapters:
  - duckdb, version 1.25.2
  - sqlite, version 1.25.2
```

What database adapter are you using with Harlequin? (Default is `duckdb`)
duckdb

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).
None.

Can you tell us more about your system?
- Shell: Fish
- Terminal: Hyper
- OS of the shell: MacOS Sequoia
- OS of the terminal (if different from the shell):
- Default locale / language for your OS/Terminal/Shell: en_US/UTF-8

> [!TIP]
> For example, for my system, these are:
> - Bash
> - Windows Terminal
> - Ubuntu 22.04 / WSL2
> - Windows 11
> - en_US/UTF-8

How did you install Harlequin?
- [x] pipx
- [ ] conda/mamba
- [ ] pip (global install)
- [ ] pip + venv/virtualenv or pipenv
- [ ] Poetry
- [ ] uv/Rye
- [ ] other: _____________

**Comment by tconbeer** [comment]
yeah, I'm sorry about this; it's a known issue: https://github.com/tconbeer/harlequin/discussions/444

basically, the upstream package we depend on for syntax highlighting isn't very good. Unfortunately there aren't great, easy alternatives right now.
