### ISSUE TITLE
Harleqin crashes on startup

### ISSUE THREAD

**Issue by IvanDerdicDer** [tconbeer/harlequin#698]
**Before Proceeding, please acknowledge**:
- [x] I have consulted the [Troubleshooting guide](https://harlequin.sh/docs/troubleshooting/index).
- [x] I have searched Issues and Discussions in this repo.
- [x] Feature requests should be initiated as Discussions. This is a bug report.

**Describe the bug**
Harlequin crashes on startup. UI shows up for a second then it crashes and produces a DuckDB error.

**To Reproduce**
Start up Harlequin, wait

**Expected behavior**
It doesn't crash.

**Actual behavior**
It crashes.
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\textual\worker.py:368 in _run             │
│                                                                                                                      │
│   365 │   │   self.state = WorkerState.RUNNING                                                                       │
│   366 │   │   app.log.worker(self)                                                                                   │
│   367 │   │   try:                                                                                                   │
│ ❱ 368 │   │   │   self._result = await self.run()                                                                    │
│   369 │   │   except asyncio.CancelledError as error:                                                                │
│   370 │   │   │   self.state = WorkerState.CANCELLED                                                                 │
│   371 │   │   │   self._error = error                                                                                │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │           app = Harlequin(title='Harlequin', classes={'-dark-mode'})                                             │ │
│ │         error = InternalException("INTERNAL Error: Attempted to access index 1 within vector of size 1\nThis     │ │
│ │                 error signals an assertion failure within DuckDB. This usually occurs due to unexpected          │ │
│ │                 conditions or errors in the program's logic.\nFor more information, see                          │ │
│ │                 https://duckdb.org/docs/dev/internal_errors")                                                    │ │
│ │          self = <Worker                                                                                          │ │
│ │                 │   ERROR                                                                                        │ │
│ │                 │   name='update_completers'                                                                     │ │
│ │                 │   group='completer_builders'                                                                   │ │
│ │                 │   description='building completers'                                                            │ │
│ │                 >                                                                                                │ │
│ │     Traceback = <class 'rich.traceback.Traceback'>                                                               │ │
│ │ worker_failed = WorkerFailed('Worker raised exception: InternalException("INTERNAL Error: Attempted to access    │ │
│ │                 index 1 within vector of size 1\\nThis error signals an assertion failure within DuckDB. This    │ │
│ │                 usually occurs due to unexpected conditions or errors in the program\'s logic.\\nFor more        │ │
│ │                 information, see https://duckdb.org/docs/dev/internal_errors")')                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\textual\worker.py:352 in run              │
│                                                                                                                      │
│   349 │   │   Returns:                                                                                               │
│   350 │   │   │   Return value of the work.                                                                          │
│   351 │   │   """                                                                                                    │
│ ❱ 352 │   │   return await (                                                                                         │
│   353 │   │   │   self._run_threaded() if self._thread_worker else self._run_async()                                 │
│   354 │   │   )                                                                                                      │
│   355                                                                                                                │
│                                                                                                                      │
│ ╭────────────────────────────────────────────────── locals ───────────────────────────────────────────────────╮      │
│ │ self = <Worker ERROR name='update_completers' group='completer_builders' description='building completers'> │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯      │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\textual\worker.py:324 in _run_threaded    │
│                                                                                                                      │
│   321 │   │                                                                                                          │
│   322 │   │   loop = asyncio.get_running_loop()                                                                      │
│   323 │   │   assert loop is not None                                                                                │
│ ❱ 324 │   │   return await loop.run_in_executor(None, runner, self._work)                                            │
│   325 │                                                                                                              │
│   326 │   async def _run_async(self) -> ResultType:                                                                  │
│   327 │   │   """Run an async worker.                                                                                │
│                                                                                                                      │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮                     │
│ │          loop = <ProactorEventLoop running=True closed=False debug=False>                    │                     │
│ │ run_awaitable = <function Worker._run_threaded.<locals>.run_awaitable at 0x0000021EF3D4C540> │                     │
│ │  run_callable = <function Worker._run_threaded.<locals>.run_callable at 0x0000021EF3F8A980>  │                     │
│ │ run_coroutine = <function Worker._run_threaded.<locals>.run_coroutine at 0x0000021EF3D4F420> │                     │
│ │        runner = <function Worker._run_threaded.<locals>.run_callable at 0x0000021EF3F8A980>  │                     │
│ │          self = <Worker                                                                      │                     │
│ │                 │   ERROR                                                                    │                     │
│ │                 │   name='update_completers'                                                 │                     │
│ │                 │   group='completer_builders'                                               │                     │
│ │                 │   description='building completers'                                        │                     │
│ │                 >                                                                            │                     │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯                     │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py:58 in run                  │
│                                                                                                                      │
│    55 │   │   │   return                                                                       ╭── locals ───╮       │
│    56 │   │                                                                                    │ self = None │       │
│    57 │   │   try:                                                                             ╰─────────────╯       │
│ ❱  58 │   │   │   result = self.fn(*self.args, **self.kwargs)                                                        │
│    59 │   │   except BaseException as exc:                                                                           │
│    60 │   │   │   self.future.set_exception(exc)                                                                     │
│    61 │   │   │   # Break a reference cycle with the exception 'exc'                                                 │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\textual\worker.py:307 in run_callable     │
│                                                                                                                      │
│   304 │   │   def run_callable(work: Callable[[], ResultType]) -> ResultType:                                        │
│   305 │   │   │   """Set the active worker, and call the callable."""                                                │
│   306 │   │   │   active_worker.set(self)                                                                            │
│ ❱ 307 │   │   │   return work()                                                                                      │
│   308 │   │                                                                                                          │
│   309 │   │   if (                                                                                                   │
│   310 │   │   │   inspect.iscoroutinefunction(self._work)                                                            │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │ self = <Worker ERROR name='update_completers' group='completer_builders' description='building completers'>      │ │
│ │ work = functools.partial(<function Harlequin.update_completers at 0x0000021EF338A3E0>,                           │ │
│ │        Harlequin(title='Harlequin', classes={'-dark-mode'}),                                                     │ │
│ │        Catalog(items=[CatalogItem(qualified_identifier='"memory"', query_name='"memory"', label='memory',        │ │
│ │        type_label='db', children=[CatalogItem(qualified_identifier='"memory"."main"',                            │ │
│ │        query_name='"memory"."main"', label='main', type_label='sch', children=[])])]))                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\harlequin\app.py:1002 in                  │
│ update_completers                                                                                                    │
│                                                                                                                      │
│    999 │   │   │   self.editor_collection.word_completer.update_catalog(catalog=catalog)                             │
│   1000 │   │   │   self.editor_collection.member_completer.update_catalog(catalog=catalog)                           │
│   1001 │   │   else:                                                                                                 │
│ ❱ 1002 │   │   │   extra_completions = self.connection.get_completions()                                             │
│   1003 │   │   │   word_completer, member_completer = completer_factory(                                             │
│   1004 │   │   │   │   catalog=catalog,                                                                              │
│   1005 │   │   │   │   extra_completions=extra_completions,                                                          │
│                                                                                                                      │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                                            │
│ │ catalog = Catalog(                                                    │                                            │
│ │           │   items=[                                                 │                                            │
│ │           │   │   CatalogItem(                                        │                                            │
│ │           │   │   │   qualified_identifier='"memory"',                │                                            │
│ │           │   │   │   query_name='"memory"',                          │                                            │
│ │           │   │   │   label='memory',                                 │                                            │
│ │           │   │   │   type_label='db',                                │                                            │
│ │           │   │   │   children=[                                      │                                            │
│ │           │   │   │   │   CatalogItem(                                │                                            │
│ │           │   │   │   │   │   qualified_identifier='"memory"."main"', │                                            │
│ │           │   │   │   │   │   query_name='"memory"."main"',           │                                            │
│ │           │   │   │   │   │   label='main',                           │                                            │
│ │           │   │   │   │   │   type_label='sch',                       │                                            │
│ │           │   │   │   │   │   children=[]                             │                                            │
│ │           │   │   │   │   )                                           │                                            │
│ │           │   │   │   ]                                               │                                            │
│ │           │   │   )                                                   │                                            │
│ │           │   ]                                                       │                                            │
│ │           )                                                           │                                            │
│ │    self = Harlequin(title='Harlequin', classes={'-dark-mode'})        │                                            │
│ ╰───────────────────────────────────────────────────────────────────────╯                                            │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\harlequin_duckdb\adapter.py:188 in        │
│ get_completions                                                                                                      │
│                                                                                                                      │
│   185 │   │   │   │   priority=priority,                                                                             │
│   186 │   │   │   │   context=context,                                                                               │
│   187 │   │   │   )                                                                                                  │
│ ❱ 188 │   │   │   for label, type_label, priority, context in get_completion_data(cur)                               │
│   189 │   │   ]                                                                                                      │
│   190 │                                                                                                              │
│   191 │   def validate_sql(self, text: str) -> str:                                                                  │
│                                                                                                                      │
│ ╭──────────────────────────────────── locals ─────────────────────────────────────╮                                  │
│ │  cur = <duckdb.duckdb.DuckDBPyConnection object at 0x0000021EF3F351B0>          │                                  │
│ │ self = <harlequin_duckdb.adapter.DuckDbConnection object at 0x0000021EF167E780> │                                  │
│ ╰─────────────────────────────────────────────────────────────────────────────────╯                                  │
│                                                                                                                      │
│ C:\Users\iderdic\AppData\Local\Programs\Python\Python312\Lib\site-packages\harlequin_duckdb\completions.py:51 in     │
│ get_completion_data                                                                                                  │
│                                                                                                                      │
│   48 │   │   """                                                                                                     │
│   49 │   ).fetchall()                                                                                                │
│   50 │                                                                                                               │
│ ❱ 51 │   type_data = cur.execute(                                                                                    │
│   52 │   │   """                                                                                                     │
│   53 │   │   with                                                                                                    │
│   54 │   │   │   system_types as (                                                                                   │
│                                                                                                                      │
│ ╭──────────────────────────────────── locals ─────────────────────────────────────╮                                  │
│ │           cur = <duckdb.duckdb.DuckDBPyConnection object at 0x0000021EF3F351B0> │                                  │
│ │ function_data = [                                                               │                                  │
│ │                 │   ('read_blob', 'fn->T', 1000, None),                         │                                  │
│ │                 │   ('tpch_answers', 'fn->T', 1000, None),                      │                                  │
│ │                 │   ('read_parquet', 'fn->T', 1000, None),                      │                                  │
│ │                 │   ('pragma_show', 'fn->T', 1000, None),                       │                                  │
│ │                 │   ('duckdb_constraints', 'fn->T', 1000, None),                │                                  │
│ │                 │   ('dbgen', 'fn->T', 1000, None),                             │                                  │
│ │                 │   ('read_json', 'fn->T', 1000, None),                         │                                  │
│ │                 │   ('parquet_kv_metadata', 'fn->T', 1000, None),               │                                  │
│ │                 │   ('row', 'fn', 1000, None),                                  │                                  │
│ │                 │   ('sqrt', 'fn', 1000, None),                                 │                                  │
│ │                 │   ... +976                                                    │                                  │
│ │                 ]                                                               │                                  │
│ │  keyword_data = [                                                               │                                  │
│ │                 │   ('all', 'kw', 100, None),                                   │                                  │
│ │                 │   ('always', 'kw', 1000, None),                               │                                  │
│ │                 │   ('analyze', 'kw', 100, None),                               │                                  │
│ │                 │   ('assignment', 'kw', 1000, None),                           │                                  │
│ │                 │   ('asymmetric', 'kw', 100, None),                            │                                  │
│ │                 │   ('authorization', 'kw', 1000, None),                        │                                  │
│ │                 │   ('backward', 'kw', 1000, None),                             │                                  │
│ │                 │   ('between', 'kw', 1000, None),                              │                                  │
│ │                 │   ('call', 'kw', 1000, None),                                 │                                  │
│ │                 │   ('cast', 'kw', 100, None),                                  │                                  │
│ │                 │   ... +470                                                    │                                  │
│ │                 ]                                                               │                                  │
│ │ settings_data = [                                                               │                                  │
│ │                 │   ('default_order', 'set', 2000, None),                       │                                  │
│ │                 │   ('force_compression', 'set', 2000, None),                   │                                  │
│ │                 │   ('ieee_floating_point_ops', 'set', 2000, None),             │                                  │
│ │                 │   ('immediate_transaction_mode', 'set', 2000, None),          │                                  │
│ │                 │   ('max_temp_directory_size', 'set', 2000, None),             │                                  │
│ │                 │   ('max_vacuum_tasks', 'set', 2000, None),                    │                                  │
│ │                 │   ('old_implicit_casting', 'set', 2000, None),                │                                  │
│ │                 │   ('order_by_non_integer_literal', 'set', 2000, None),        │                                  │
│ │                 │   ('password', 'set', 2000, None),                            │                                  │
│ │                 │   ('pivot_filter_threshold', 'set', 2000, None),              │                                  │
│ │                 │   ... +94                                                     │                                  │
│ │                 ]                                                               │                                  │
│ ╰─────────────────────────────────────────────────────────────────────────────────╯                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the
program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [ ] Maybe
- [x] No

**Additional context**
*Please provide as much as you can, but don't waste your time if it's definitely not relevant or you don't know.*

What is the output of `harlequin --version`?
harlequin, version 1.24.0

Installed Adapters:
  - duckdb, version 1.24.0
  - sqlite, version 1.24.0

What database adapter are you using with Harlequin? (Default is `duckdb`)
duckdb

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).
None

Can you tell us more about your system?
- Shell: NuShell
- Terminal: Windows Terminal
- OS of the shell: Windows 11
- Default locale / language for your OS/Terminal/Shell: English

> [!TIP]
> For example, for my system, these are:
> - Bash
> - Windows Terminal
> - Ubuntu 22.04 / WSL2
> - Windows 11
> - en_US/UTF-8

How did you install Harlequin?
- [ ] pipx
- [ ] conda/mamba
- [x] pip (global install)
- [ ] pip + venv/virtualenv or pipenv
- [ ] Poetry
- [ ] uv/Rye
- [ ] other: _____________

**Comment by tconbeer** [comment]
See https://github.com/tconbeer/harlequin/discussions/643

Please upgrade duckdb to v 1.1.1 or higher. 

pip install --upgrade duckdb
