### ISSUE TITLE
Support pasting from the system clipboard

### ISSUE THREAD

**Issue by ned2** [tconbeer/harlequin#73]
Currently Harlequin's query editor only supports pasting from text that has been already copied within the query editor. A common use case for SQL editors is copying SQL snnippets from the system clipboard, so this should be supported.

I can see from the doc string of the [on_paste](https://github.com/tconbeer/harlequin/blob/main/src/harlequin/tui/components/textarea.py#L70) function in `tui/components/textarea.py` that this is a known limitation, but thought I'd create an issue to save others trying to work out if this is a bug or known limitation.

When I initiate a copy event I can see that the `event` param passed to the `on_paste` function has my copied text from the system clipboard in its `text` attribute, so hopefully that means all the ingredients are there ready to add this feature.

**Comment by tconbeer** [comment]
Duplicates #53

**Comment by ned2** [comment]
ah sorry, missed that
