### ISSUE TITLE
Unexpected behavior from Windows keyboard input

### ISSUE THREAD

**Issue by wuxunfeng666** [tconbeer/harlequin#82]
Hi. I encountered two problems when I use harlequin on Windows:

1. I can't enter even one line of code smoothly. There seems to be a problem with the formatting.
2. Sometimes the editor exits abnormally. For example, pressing the <kbd>Ctrl</kbd> when there is no content.

![record.webp](https://github.com/tconbeer/harlequin/assets/25447739/07e20051-ebde-494c-9ac4-36c73384ff4e)

**Comment by tconbeer** [comment]
The video is going too fast for me to see what is going on. Can you please provide 1 or 2 reproducible scenarios that produce unexpected results?

Also:
- What keyboard (language/layout) are you using? I see some non-Latin characters in the captions
- If you are using command prompt, can you try with Powershell instead? (Powershell in windows terminal should work fine)

**Comment by wuxunfeng666** [comment]
Thanks for your reply. Here's what I did in the video, and what happened:

1. The SQL I wanted to run was:

   ```sql
   select * from range(3);
   ```

   And I typed:

   > `select` <kbd>Space</kbd> <kbd>Shift + 8</kbd> <kbd>Space</kbd> `from` <kbd>Space</kbd> `range` <kbd>Shift + 9</kbd> `3` <kbd>Shift + 0</kbd> `;` <kbd>Ctrl + Enter</kbd>

   The result seems to be that when the <kbd>Shift</kbd> is pressed, the cursor will move back one character, causing `*` and `(` to appear in the wrong place.

   But the strange thing is that, a `space` will be automatically added in front of the `*` later, and the `)` is in the correct position.

2. When there was no content in the editor, I pressed the <kbd>Ctrl</kbd>, then harlequin exited abnormally.

For your question:

1. I am using Chinese keyboard.
2. I tried PowerShell, but the result is the same as cmd.

**Comment by tconbeer** [comment]
Thanks for the info. There must be an issue with how the terminal is interpreting the input from your keyboard. We're clearly getting extra key press events that aren't caused by you. 

We might be able to figure some of it out using the textual keys app, but I don't really know where this will take us. I'm going to ask for some help and understand what other Textual developers are doing to support other keyboards

**Comment by tconbeer** [comment]
ok, I actually was able to reproduce this; on windows, every press of `shift` is interpreted as `ctrl+@`, which we had mapped to the format action.
