### ISSUE TITLE
Add multi-database support

### ISSUE THREAD

**Issue by ywelsch** [tconbeer/harlequin#89]
DuckDB has support for [attaching multiple databases](https://duckdb.org/docs/sql/statements/attach). The catalog UI currently only takes the default DB into account. It would be great to show all databases/catalogs and their schemas on the left hand side, with the current default database highlighted.

**Comment by tconbeer** [comment]
Seems that the [docs](https://duckdb.org/docs/sql/information_schema) are wrong, and `table_catalog` is implemented in `information_schema.tables`, so this should be a very easy add.

![image](https://github.com/tconbeer/harlequin/assets/705906/64f6e2bb-ddfe-47ab-bfa5-c2fcf0e33a00)

**Comment by ywelsch** [comment]
A minor gotcha is that the catalog view `information_schema.schemata` is still needed for catalogs/DBs that do not have tables yet. `current_database() / current_catalog()` can be used to identify the current DB.

**Comment by tconbeer** [comment]
@ywelsch This has been released in 0.0.14. Thanks for your issue!

**Comment by ywelsch** [comment]
Awesome! I've tried it out, works perfectly. Thank you.
